services:
    - type: web
      name: laravel-api
      env: docker
      plan: free
      region: oregon
      dockerfilePath: ./Dockerfile
      dockerContext: .
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_KEY
            generateValue: true
          - key: APP_DEBUG
            value: false
          - key: DB_CONNECTION
            value: mysql
          - key: DB_HOST
            value: your-db-host.render.com
          - key: DB_PORT
            value: 3306
          - key: DB_DATABASE
            value: your_database
          - key: DB_USERNAME
            value: your_user
          - key: DB_PASSWORD
            value: your_password
